apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example-daemon
  labels:
    name: front_end
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        name: nginx-pod
        app: webapp
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 9090
