apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-webpage
  labels:
    author: cicdclouds
    app_type: frontend-webpage   
spec:
  replicas: 2
  selector: 
    matchLabels:
      app_type: frontend-webpage 
  template: 
    metadata:
      name: nginx-pods
      labels:
        app_type: frontend-webpage
    spec:
      containers:
        - name: mynginx-webpage 
          image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: custom-node-label 
                    operator: In
                    values:
                      - cicdclouds-node 