apiVersion: v1
kind: Pod
metadata:
  name: nginx-pods
  labels:
    author: cicdclouds
    type: frontend_webpage
spec:
  containers:
    - name: frontend_webpage
      image: nginx
      ports:
        - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: slave1  
                operator: In
                values:
                  - cicdclouds 