apiVersion: v1
kind: PersistentVolume
metadata:
  name: taste-pv-volume
  labels:
    type: local # Changed 'null' to 'local' (or any other meaningful string)
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data