apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pods
  labels:
    type: qulitytest-server
    author: cicdclouds
spec:
  containers:
    - name: mytmcatpod
      image: tomee
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
