apiVersion: v1
kind: Pod
metadata: 
  name: pods-nginx
  labels:
    type: frontend_server
    author: cicdclouds
containers: 
  - name: nginxsever
    image: nginx
    resources:
       requests:
        memory: 64Mi
        cpu: 250m
       limits:
        memory: 128mi
        cpu: 500m
    
