---
apiVersion: v1
kind: Secret
metadata:
  name: pods-secret
  labels:
    app: my-app
type: Opaque
stringData:
  password: xxxxxx
  username: myuser
  dbname: mydb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    type: backend-server
spec:
  replicas: 3
  selector:
    matchLabels:
      type: backend-server
  template:
    metadata:
      labels:
        type: backend-server
    spec:
      containers:
        - name: database
          image: mysql
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: pods-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pods-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: pods-secret
                  key: dbname

