apiVersion: apps/v1
kind: Deployment
metadata:
  name: weberserver
  labels:
    author: cicdclouds
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      author: cicdclouds
  template:
    metadata:
      labels:
        app: webapp
        author: cicdclouds
    spec:
      containers:
        - name: httpd-server
          image: httpd
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-server
  labels:
    app: webapp
    author: cicdclouds
spec:
  type: NodePort 
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30002
  selector:
    app: webapp
    author: cicdclouds
